baseURL = 'https://stabby.binarycartel.com'
languageCode = 'en-us'
title = 'Binary Cartel'
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
publishdir = "docs/"

[Params]
  homeTitle = "binarycartel" # Set a different text for the header on the home page
  subtitle = "Game development studio working on our first title: Stabby"
  #mainSections = ["post","posts"]
  #logo = "smallbrand.png" # Expecting square dimensions
  #brand = "brand.png"
  #favicon = "hotdoglogo.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
  author.name = "binarycartel"

#[[Params.bigimg]]
  #src = "rba/kayart5000x2812-nologo.png"
  #desc = "Rightfully, Beary Arms"

[Author]
  
  github = "Binary-Cartel"
  email = "binarycartel@gmail.com"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "games"
  name = "games"
  url = "/games/stabby/"
  weight = 2

[[menu.main]]
  identifier = "rba"
  parent = "games"
  name = "stabby knight"
  url = "/games/stabby/"
  weight = 1

[[menu.main]]
  identifier = "presskit"
  name = "Press Kit"
  url = "https://press.daylightbasementstudio.com"
  weight = 4

[[menu.main]]
  identifier = "rbaPress"
  parent = "presskit"
  name = "stabby"
  url = "https://press.rbagame.com"
  weight = 1

#[[menu.main]]
#  identifier = "dbsPress"
#  parent = "presskit"
#  name = "Daylight Basement Studio"
#  url = "https://press.daylightbasementstudio.com"
#  weight = 2


[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 4

#[[menu.main]]
#  identifier = "socials"
#  name = "socials"
#  url = "https://linktr.ee/daylightbasementstudio"
#  weight = 5

#[[menu.main]]
#identifier = "merch"
#name = "merch"
#url = "https://daylightbasementstudio.square.site"
#weight = 6


[[module.imports]]
  path = "github.com/halogenica/beautifulhugo"